blank_issues_enabled: false
contact_links:
  - name: â“ Support Question
    url: https://community.serversideup.net/c/get-help/amplitudejs/27
    about: Get friendly support from the community on our forum.

  - name: ğŸ¤µ Get Professional Support & Customizations
    url: https://521dimensions.com/open-source/amplitudejs/docs/get-help/#professional-support
    about: Skip the line and get priority support directly from the creators of AmplitudeJS.