blank_issues_enabled: false
contact_links:
  - name: â“ Support Question
    url: https://community.serversideup.net/c/get-help/amplitudejs/27
    about: Get fast & friendly support on our community forum.